using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Carteira.Infrastructure.Persistence.Migrations
{
    public partial class AddOrderSequence : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE orders
                ADD COLUMN "Sequence" bigint GENERATED BY DEFAULT AS IDENTITY;

                WITH numbered AS (
                    SELECT "Id",
                           ROW_NUMBER() OVER (
                               ORDER BY "CreatedAt", "Id"
                           ) AS sequence_number
                    FROM orders
                )
                UPDATE orders AS o
                SET "Sequence" = numbered.sequence_number
                FROM numbered
                WHERE o."Id" = numbered."Id";

                SELECT setval(
                    pg_get_serial_sequence('orders', 'Sequence'),
                    COALESCE((SELECT MAX("Sequence") FROM orders), 1),
                    EXISTS(SELECT 1 FROM orders)
                );
                """);

            migrationBuilder.CreateIndex(
                name: "IX_orders_Sequence",
                table: "orders",
                column: "Sequence",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_orders_Sequence",
                table: "orders");

            migrationBuilder.DropColumn(
                name: "Sequence",
                table: "orders");
        }
    }
}
